### ISSUE TITLE
how to change Mqtt5Client to Mqtt3Client ?

### ISSUE THREAD

**Issue by liveforownhappiness** [dream-sports-labs/d11-react-native-mqtt#6]

**Comment by princektripathi** [comment]
Duplicate issue - https://github.com/dream-sports-labs/d11-react-native-mqtt/issues/9

**Comment by princektripathi** [comment]
@liveforownhappiness, we use `HiveMQ` and `CocoaMQTT` for Android and iOS respectively. Both of these use MQTT5 client and are compatible with MQTT 5 and 3.1.1

If the current offerings doesn't suffice your requirement, please share your use-case. We would be happy to enable you.
