### ISSUE TITLE
ios issue: `mqttx_d11_rn_mqttconnected` is not a supported event type for MqttModule

### ISSUE THREAD

**Issue by Hans-Sifely** [dream-sports-labs/d11-react-native-mqtt#8]
I have integrated the library and try to follow the code from the example. But I got error: "`mqttx_d11_rn_mqttconnected` is not a supported event type for MqttModule. Supported events are: `CUSTOM_EVENT`"
<img src="https://github.com/user-attachments/assets/bef0458c-20a3-4728-958e-e89a126aaa35" width="300"/>

But looks like the mqtt connection is working, I can receive the message from the MQTT server:
<img src="https://github.com/user-attachments/assets/8469dcb9-317b-4164-803f-13e1b5b2cb2e" width="300"/>

Here is my code:
![image](https://github.com/user-attachments/assets/81183093-2b2e-46e8-a2dc-9d5dc1d4c194)

Does anyone know how to fix it? Thanks

**Comment by Hans-Sifely** [comment]
+1

**Comment by RyQuantum** [comment]
+1

**Comment by princektripathi** [comment]
@Hans-Sifely , can you please share a repro for this issue?

**Comment by korayaggul** [comment]
+1

**Comment by Jidahan** [comment]
+1

**Comment by Jidahan** [comment]
> +1

Was it finally solved?

**Comment by Jidahan** [comment]
> +1

Was it finally solved?

**Comment by Jidahan** [comment]
> I have integrated the library and try to follow the code from the example. But I got error: "`mqttx_d11_rn_mqttconnected` is not a supported event type for MqttModule. Supported events are: `CUSTOM_EVENT`" <img alt="" width="300" src="https://private-user-images.githubusercontent.com/152159694/392418738-bef0458c-20a3-4728-958e-e89a126aaa35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUzMDg0NTAsIm5iZiI6MTc0NTMwODE1MCwicGF0aCI6Ii8xNTIxNTk2OTQvMzkyNDE4NzM4LWJlZjA0NThjLTIwYTMtNDcyOC05NThlLWU4OWExMjZhYWEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyMlQwNzQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGE2YjU1NTdmZTQ5MTJhY2M4YWE1YzExYjY4N2NjYzBmY2E5MDUzNjliMGE3ZDcwZWQzYTRkMDA2YTQ2ODY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qsELgt8eBllt9fOFHt2J71YjrMDZiNYuVES4seoRtU0">
> 
> But looks like the mqtt connection is working, I can receive the message from the MQTT server: <img alt="" width="300" src="https://private-user-images.githubusercontent.com/152159694/392419232-8469dcb9-317b-4164-803f-13e1b5b2cb2e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDUzMDg0NTAsIm5iZiI6MTc0NTMwODE1MCwicGF0aCI6Ii8xNTIxNTk2OTQvMzkyNDE5MjMyLTg0NjlkY2I5LTMxN2ItNDE2NC04MDNmLTEzZTFiNWIyY2IyZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDQyMlQwNzQ5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjcwMDlmOWRjMGVlZDNlMTE2ZGJjNzY2OTliMjViZTg3YTJmZDI3YmI4YzczOGI1NGMxMjFjYTE0Y2Y4ZjAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hbjv_vuVQErTizmJX91riMQP8icsEst7jP9SHl04irE">
> 
> Here is my code: ![image](https://github.com/user-attachments/assets/81183093-2b2e-46e8-a2dc-9d5dc1d4c194)
> 
> Does anyone know how to fix it? Thanks

Was it finally solved?
