### ISSUE TITLE
 library Currently supports only MQTT Version 5 ? 

### ISSUE THREAD

**Issue by KartikDevarde2601** [dream-sports-labs/d11-react-native-mqtt#9]
We are currently running an MQTT broker on an ESP32 device that supports only MQTT 3. Additionally, many libraries we rely on are outdated or no longer actively maintained.

 **any  guidance on converting MQTT 5 messages to MQTT 3,**
### Missing Implementation
 as the current library lacks support for bidirectional communication. Notably, the publish method is missing, which is crucial for effective MQTT communication.

**Comment by mayankkush1** [comment]
Hey @KartikDevarde2601 my team would love to help you with this. cc: @princektripathi

**Comment by KartikDevarde2601** [comment]
I have basic knowledge of Android Native development and attempted to convert the hivemq.client.mqtt5 implementation to hivemq.client.mqtt3 in Android. However, the build fails every time I try.

Could you provide guidance on how to navigate the repository and understand its flow better? Are there any prerequisite concepts or specific knowledge I should focus on to better comprehend the repo?

Additionally, I noticed that the library seems to lack an implementation for the publish method. Could you clarify why this might be the case?

**Comment by mayankkush1** [comment]
Hey @KartikDevarde2601 are you using this library in Android app or react-native app?

**Comment by mayankkush1** [comment]
Hey @KartikDevarde2601, can you help us with your stack trace and a reproducer app to help us debug this issue better?

**Comment by KartikDevarde2601** [comment]
Hi @mayankkush1,

I successfully converted MQTT 5 to MQTT 3 for Android ... Now, I'm working on adding the Publish method / API So learning about JSI (JavaScript Interface). Could you share some good resources to help me understand JSI better?

**Comment by princektripathi** [comment]
> Hi @mayankkush1, @princektripathi
> 
> I successfully converted MQTT 5 to MQTT 3 for Android ... Now, I'm working on adding the Publish method / API So learning about JSI (JavaScript Interface). Could you share some good resources to help me understand JSI better?

Great work @KartikDevarde2601. We would be happy to enable you. I suggest you to leverage LinkedIn for further communication regarding learning resources.

**Comment by KartikDevarde2601** [comment]
Thank you very much, @mayankkush1.

**Comment by KartikDevarde2601** [comment]
Hi @princektripathi and @mayankkush1,

I’m working on implementing the publish method, but I'm struggling with the bare-bones JSI implementation used in this repository. I’m having difficulty understanding both the JSI and JNI bindings in Android.

I attempted to implement the publish method by looking at existing examples, but the app crashed when invoking the function from JavaScript. Unfortunately, I can't find any resources that cover a bare-bones JSI implementation.

Could you please share any resources or guidance on this topic? 

Any help would be appreciated!

**Comment by princektripathi** [comment]
@KartikDevarde2601, definitely. We would be happy to enable you.  Please join our Discord server - https://discord.gg/ER5wCarE

**Comment by KartikDevarde2601** [comment]
ok
